allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@posthog/types@1.404.0'
  - posthog-js@1.417.0
  - '@posthog/core@1.48.0'

overrides:
  'postcss': 'npm:postcss@8.5.23'
  'sharp': 'npm:sharp@0.35.3'
  'brace-expansion': 'npm:brace-expansion@5.0.8'
  'minimatch': 'npm:minimatch@10.2.5'
