ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw

overrides:
  'postcss': 'npm:postcss@8.5.15'
  'esbuild': 'npm:esbuild@0.28.1'
