allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  unrs-resolver: true
  workerd: true

minimumReleaseAgeExclude:
  - '@posthog/types@1.404.0'
  - posthog-js@1.417.0
  - '@posthog/core@1.48.0'
  - baseline-browser-mapping@2.11.25
  - electron-to-chromium@1.5.431
  - node-releases@2.0.56

overrides:
  'browserslist': 'npm:browserslist@4.29.0'
