import { clientEnvSchema } from '@/schemas/env'

export const clientEnv = clientEnvSchema.parse({
  // Metadata
  NEXT_PUBLIC_APP_NAME: process.env.NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_APP_DEFAULT_TITLE: process.env.NEXT_PUBLIC_APP_DEFAULT_TITLE,
  NEXT_PUBLIC_APP_TITLE_TEMPLATE: process.env.NEXT_PUBLIC_APP_TITLE_TEMPLATE,
  NEXT_PUBLIC_APP_DESCRIPTION: process.env.NEXT_PUBLIC_APP_DESCRIPTION,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_APP_PORT: process.env.NEXT_PUBLIC_APP_PORT,

  // Supabase
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,

  // Posthog
  NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN: process.env.NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN,
  NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST,
})
